# syntax=docker/dockerfile:1.5
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/app/.npm \
	npm set cache /app/.npm && \
	npm install

COPY . . 

EXPOSE 3000

CMD ["npm", "run", "dev"]
